# BD-BOMBS VERSION 1.0
# CONTACT ME ON FACEBOOK USING FOR THIS TOOLS
# CREATED BY ADIL ARHAM SHORIF (STR4NG3R)
# IF YOU WANNA TAKE CREDITS FOR THIS CODE, PLEASE LOOK YOURSELF AGAIN...
# ALL RIGHT RESERVED BY 2021
# POWERED BY TEAM BADS - SECURITY RESEARCHERS
import os
os.system("python2 .STR4NG3R.PY")
# BD-BOMBS VERSION 1.0
# CONTACT ME ON FACEBOOK USING FOR THIS TOOLS
# CREATED BY ADIL ARHAM SHORIF (STR4NG3R)
# IF YOU WANNA TAKE CREDITS FOR THIS CODE, PLEASE LOOK YOURSELF AGAIN...
# ALL RIGHT RESERVED BY 2021
# POWERED BY TEAM BADS - SECURITY RESEARCHERS
