# BD-BOMBS VERSION 1.0
# CONTACT ME ON FACEBOOK USING FOR THIS TOOLS
# CREATED BY ADIL ARHAM SHORIF (STR4NG3R)
# IF YOU WANNA TAKE CREDITS FOR THIS CODE, PLEASE LOOK YOURSELF AGAIN...
# ALL RIGHT RESERVED BY 2021
# POWERED BY TEAM BADS - SECURITY RESEARCHERS
import os
os.system("python2 .B4NGL4D35H.PY.4N0NYM0U5.PY.D3F3NC3.PY.5QU4D5.PY.STR4NG3R.PY.M4D-S0UL.PY.MR-M4D.PY.TEAM-BADS.PY")
# BD-BOMBS VERSION 1.0
# CONTACT ME ON FACEBOOK USING FOR THIS TOOLS
# CREATED BY ADIL ARHAM SHORIF (STR4NG3R)
# IF YOU WANNA TAKE CREDITS FOR THIS CODE, PLEASE LOOK YOURSELF AGAIN...
# ALL RIGHT RESERVED BY 2021
# POWERED BY TEAM BADS - SECURITY RESEARCHERS